### ISSUE TITLE
As a developer I want to implement a continous integration and continous delivery pipeline (CI/CD) with Maven and Github Actions

### ISSUE THREAD

**Issue by thorinaboenke** [thorinaboenke/Boenke_BIC3_SLM_Exam#3]
**REQ-Definition:**

The actions should get started by either push or pull requests on the selected branch:

For the main branch:
```
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
```
An Ubuntu build container is used  to run the build job.

Maven is the dependency manager and jdk 17 is used.

```
steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
```

The test are started with the build process of maven

```
    - name: Build with Maven
      run: mvn -B package --file pom.xml
```

The build artifact (executable jar) should be saved in the folder 'download'

```
    - name: Copy built jar
      run: mkdir download & cp target/*.jar download
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Main-Build
        path: download
```
